//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int Id { get; set; }
        public Nullable<int> DemandId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<bool> DemandAccept { get; set; }
        public Nullable<bool> OfferAccept { get; set; }
        public Nullable<double> Commission { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
